# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
custom_type_derives = ["Clone", "diesel::query_builder::QueryId"]
file = "src/schema.rs"

[migrations_directory]
dir = "/home/dave/dev/bpfman/bpfman/migrations"
